# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
#
# GoReleaser configuration for AgenticFleet
# This config focuses on changelog generation and GitHub releases
# since the actual Python package build/publish is handled by uv
#
# Usage:
#   goreleaser check                    # Validate this config
#   goreleaser release --snapshot       # Test release locally
#   goreleaser release                  # Create a release (CI)

version: 2

project_name: agentic-fleet

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

# Skip Go builds since this is a Python project
builds:
  - skip: true

# Changelog configuration
changelog:
  # Use conventional commits for grouping
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "typo"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "⚡ Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "♻️ Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "🔒 Security"
      regexp: '^.*?security(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "📦 Dependencies"
      regexp: '^.*?(deps|build\(deps\))(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "🔧 Other Changes"
      order: 999

# GitHub release configuration
release:
  github:
    owner: Qredence
    name: agentic-fleet
  # Use auto-generated release notes from changelog
  draft: false
  prerelease: auto
  mode: replace
  # Include the Python distribution files if they exist
  extra_files:
    - glob: dist/*.whl
    - glob: dist/*.tar.gz
  name_template: "AgenticFleet {{ .Tag }}"
  header: |
    ## AgenticFleet {{ .Tag }}

    Multi-agent orchestration system built with Microsoft Agent Framework's Magentic Fleet pattern.

    ### Installation

    ```bash
    # Using pip
    pip install agentic-fleet=={{ .Version }}

    # Using uv
    uv add agentic-fleet=={{ .Version }}
    ```

  footer: |
    ---
    **Full Changelog**: https://github.com/Qredence/agentic-fleet/compare/{{ .PreviousTag }}...{{ .Tag }}

# Announce releases (optional - configure tokens in CI)
# announce:
#   discord:
#     enabled: false
#   slack:
#     enabled: false

# Git configuration
git:
  # Only consider tags matching semver
  tag_sort: -version:refname
  prerelease_suffix: "-"
  ignore_tags:
    - nightly
    - latest

# Validate before release
before:
  hooks:
    # Ensure dist directory exists for Python artifacts
    - mkdir -p dist

# Milestones (optional - link releases to GitHub milestones)
milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
