# Use the official Python image as the base
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install playwright dependencies
RUN python -m playwright install-deps

# Copy the project files into the container
COPY . .

# Expose the port Chainlit runs on (default is 8000)
EXPOSE 8000

# Set environment variables (using ARG for build-time flexibility, with defaults)
ARG OPENAI_API_KEY=""
ARG AZURE_OPENAI_ENDPOINT=""
ARG AZURE_OPENAI_API_KEY=""
ARG AZURE_OPENAI_DEPLOYMENT=""
ARG AZURE_OPENAI_MODEL=""
ARG AZURE_OPENAI_API_VERSION=""
ARG USE_OAUTH=""
ARG OAUTH_PROVIDER=""
ARG OAUTH_PROMPT=""
ARG OAUTH_GITHUB_CLIENT_ID=""
ARG OAUTH_GITHUB_CLIENT_SECRET=""
ARG OAUTH_REDIRECT_URI=""

# Azure OpenAI Configuration
ARG AZURE_AI_PHI_MODEL=""
ARG AZURE_AI_DEEPSEEK_R1_MODEL=""
ARG AZURE_AI_FOUNDRY_MODEL=""
ARG AZURE_AI_FOUNDRY_API_VERSION=""
ARG AZURE_AI_FOUNDRY_API_KEY=""
ARG POOL_MANAGEMENT_ENDPOINT=""
ARG GITHUB_TOKEN=""
ARG DB_USER=""
ARG DB_PASSWORD=""
ARG DB_HOST=""
ARG DB_PORT=""
ARG DB_NAME=""
ARG GITHUB_CLIENT_ID=""
ARG GITHUB_CLIENT_SECRET=""
ARG GOOGLE_CLIENT_ID=""
ARG GOOGLE_CLIENT_SECRET=""


ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
ENV AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
ENV AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
ENV AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
ENV AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
ENV USE_OAUTH=${USE_OAUTH}
ENV OAUTH_PROVIDER=${OAUTH_PROVIDER}
ENV OAUTH_PROMPT=${OAUTH_PROMPT}
ENV OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
ENV OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
ENV OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
ENV AZURE_AI_PHI_MODEL=${AZURE_AI_PHI_MODEL}
ENV AZURE_AI_DEEPSEEK_R1_MODEL=${AZURE_AI_DEEPSEEK_R1_MODEL}
ENV AZURE_AI_FOUNDRY_MODEL=${AZURE_AI_FOUNDRY_MODEL}
ENV AZURE_AI_FOUNDRY_API_VERSION=${AZURE_AI_FOUNDRY_API_VERSION}
ENV AZURE_AI_FOUNDRY_API_KEY=${AZURE_AI_FOUNDRY_API_KEY}
ENV POOL_MANAGEMENT_ENDPOINT=${POOL_MANAGEMENT_ENDPOINT}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_NAME=${DB_NAME}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

# Run the Chainlit application
CMD ["chainlit", "run", "src/agentic_fleet/app.py"]
