# AgenticFleet Workflow Configurations
# Package default configuration - can be overridden by:
# 1. AF_WORKFLOW_CONFIG environment variable (absolute path)
# 2. config/workflows.yaml (repo/deploy-level override)

workflows:
  magentic_fleet:
    name: "Magentic Fleet Workflow"
    description: "Five-agent orchestration with planner, executor, coder, verifier, and generator"
    factory: "create_magentic_fleet_workflow"

    agents:
      planner:
        model: "gpt-5-mini"
        instructions: |
          You are the planner. Break down complex requests into clear, actionable steps.
          Assign ownership and define success criteria for each step.
        description: "Decomposes the request into actionable steps and assigns ownership"
        reasoning:
          effort: "high"
          verbosity: "verbose"
        temperature: 0.5
        max_tokens: 4096
        store: true

      executor:
        model: "gpt-5-mini"
        instructions: |
          You are the executor module. Carry out the active instruction from the
          manager or planner. Execute reasoning-heavy steps, delegate to registered tools when needed,
          and produce clear artefacts or status updates. If a tool is required, call it explicitly and
          then explain the outcome.
        description: "Executes active plan steps and coordinates other specialists"
        reasoning:
          effort: "medium"
          verbosity: "verbose"
        temperature: 0.6
        max_tokens: 4096
        store: true

      coder:
        model: "gpt-5-mini"
        instructions: |
          You are the coder. Write and execute code as needed to unblock the team. Produce
          well-documented snippets, explain results, and call the hosted interpreter tool
          for calculations or data analysis.
        description: "Writes and executes code to unblock the team"
        reasoning:
          effort: "high"
          verbosity: "verbose"
        temperature: 0.3
        max_tokens: 8192
        store: true
        tools:
          - HostedCodeInterpreterTool

      verifier:
        model: "gpt-5-mini"
        instructions: |
          You are the verifier module. Inspect the current state, outputs, and
          assumptions. Confirm whether the work satisfies requirements, highlight defects or missing
          information, and suggest concrete follow-up actions.
        description: "Validates intermediate outputs and flags quality issues"
        reasoning:
          effort: "high"
          verbosity: "verbose"
        temperature: 0.5
        max_tokens: 4096
        store: true

      generator:
        model: "gpt-5-mini"
        instructions: |
          You are the generator module. Assemble the final response for the
          user. Incorporate verified outputs, cite supporting evidence when available, and ensure the
          result addresses the original request without leaking internal reasoning unless explicitly
          requested.
        description: "Synthesises verified work into the final answer"
        reasoning:
          effort: "low"
          verbosity: "verbose"
        temperature: 0.8
        max_tokens: 6144
        store: true

    manager:
      model: "gpt-5-mini"
      instructions: |
        You are the orchestrator managing a five-agent team: planner, executor, coder,
        verifier, and generator. Coordinate their work strategically to deliver comprehensive
        solutions. Leverage the planner for decomposition, executor for implementation,
        coder for technical tasks, verifier for quality assurance, and generator for synthesis.
      reasoning:
        effort: "high"
        verbosity: "verbose"
      temperature: 0.6
      max_tokens: 8192
      store: true
      max_round_count: 6
      max_stall_count: 3
      max_reset_count: 2
