"""Minimal trio workflow helper built on Microsoft Agent Framework."""

from __future__ import annotations

from .workflow import (
    COLLABORATION_CODER_INSTRUCTIONS,
    COLLABORATION_MANAGER_INSTRUCTIONS,
    COLLABORATION_RESEARCHER_INSTRUCTIONS,
    COLLABORATION_REVIEWER_INSTRUCTIONS,
    MAGENTIC_FLEET_CODER_INSTRUCTIONS,
    MAGENTIC_FLEET_DEFAULT_MODEL,
    MAGENTIC_FLEET_EXECUTOR_INSTRUCTIONS,
    MAGENTIC_FLEET_GENERATOR_INSTRUCTIONS,
    MAGENTIC_FLEET_MANAGER_INSTRUCTIONS,
    MAGENTIC_FLEET_PLANNER_INSTRUCTIONS,
    MAGENTIC_FLEET_VERIFIER_INSTRUCTIONS,
    create_collaboration_workflow,
    create_magentic_fleet_workflow,
)

__all__ = [
    "COLLABORATION_CODER_INSTRUCTIONS",
    "COLLABORATION_MANAGER_INSTRUCTIONS",
    "COLLABORATION_RESEARCHER_INSTRUCTIONS",
    "COLLABORATION_REVIEWER_INSTRUCTIONS",
    "MAGENTIC_FLEET_CODER_INSTRUCTIONS",
    "MAGENTIC_FLEET_DEFAULT_MODEL",
    "MAGENTIC_FLEET_EXECUTOR_INSTRUCTIONS",
    "MAGENTIC_FLEET_GENERATOR_INSTRUCTIONS",
    "MAGENTIC_FLEET_MANAGER_INSTRUCTIONS",
    "MAGENTIC_FLEET_PLANNER_INSTRUCTIONS",
    "MAGENTIC_FLEET_VERIFIER_INSTRUCTIONS",
    "create_collaboration_workflow",
    "create_magentic_fleet_workflow",
]

__version__ = "0.6.0"
